# Generated by Django 3.1.7 on 2021-07-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BhanuHastakalaApp', '0002_product_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feathers',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
